ERROR:root:<class 'Exception'>
Traceback (most recent call last):
  File "c:\Users\vikto\Documents\Projects\Scramble for Africa\Scramble_for_Africa.py", line 34, in <module>
    main_loop.main_loop()
  File "c:\Users\vikto\Documents\Projects\Scramble for Africa\modules\main_loop.py", line 251, in main_loop
    turn_management_utility.manage_combat()
  File "c:\Users\vikto\Documents\Projects\Scramble for Africa\modules\util\turn_management_utility.py", line 740, in manage_combat
    start_player_turn()
  File "c:\Users\vikto\Documents\Projects\Scramble for Africa\modules\util\turn_management_utility.py", line 87, in start_player_turn
    manage_financial_report()
  File "c:\Users\vikto\Documents\Projects\Scramble for Africa\modules\util\turn_management_utility.py", line 377, in manage_financial_report
    financial_report_text = constants.money_tracker.prepare_financial_report()
  File "c:\Users\vikto\Documents\Projects\Scramble for Africa\modules\tools\data_managers\value_tracker_template.py", line 184, in prepare_financial_report
    > status.transaction_history["subsidies"]
KeyError: 'subsidies'
